spring.application.name=vehicle-bidding-system

# running server
server.port=8090

# spring security
spring.security.user.name=admin
spring.security.user.password=admin123
spring.security.user.roles=ADMIN


# Datasource configuration
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=vehicle-bidding-system;encrypt=true;trustServerCertificate=true
spring.datasource.username=vehidb
spring.datasource.password=Admin123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA/Hibernate settings
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=validate
  #spring.jpa.hibernate.ddl-auto=validate -> Or 'none' to prevent any schema changes
spring.jpa.show-sql=true
  #spring.jpa.show-sql=true -> Logs SQL queries for debugging (turn off in production)
spring.jpa.properties.hibernate.format_sql=true  # Formats SQL in logs for readability

# Optional: Connection pool settings for performance (e.g., 100 users)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5