spring.application.name=vehicle-bidding-system

# running server
server.port=8090

# spring security
spring.security.user.name=admin
spring.security.user.password=admin123
spring.security.user.roles=ADMIN
